In [7]:
import numpy as np


In [18]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [19]:
def sigmoid_der(x):
    return x * (1-x)

In [35]:
input_training_data = np.array([[0,0,1],
                               [1,1,1],
                               [1,0,1],
                               [0,1,1]])

In [36]:
output_training_data = np.array([[0,1,1,0]]).T

In [37]:
np.random.seed(1)

In [38]:
weights = 2 * np.random.random((3,1))-1

In [39]:
print(weights)

[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [46]:
for iterations in range(200):
    input_layer = input_training_data
    outputs = sigmoid(np.dot(input_layer, weights))
    error = output_training_data - outputs
    adjustments = error * sigmoid_der(outputs)
    weights += np.dot(input_layer.T, adjustments)

In [47]:
print(weights)

[[12.71727672]
 [-0.20391803]
 [-6.15496445]]


In [48]:
print(outputs)

[[0.00211842]
 [0.99827084]
 [0.99858937]
 [0.00172831]]
